version: 2

defaults: &defaults
  docker:
    - image: circleci/clojure:lein-2.9.1
  working_directory: ~/topology-grapher

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - grapher-{{ checksum "project.clj" }}

      - run: sudo apt update && sudo apt install graphviz
      - run: lein deps
      - run: lein eastwood
      - run: lein cljfmt check
      - run: lein kaocha --plugin kaocha.plugin/junit-xml --junit-xml-file test-results/kaocha/results.xml
      - store_test_results:
          path: test-results

      - save_cache:
          paths:
            - ~/.m2
          key: grapher-{{ checksum "project.clj" }}

  coverage:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - grapher-{{ checksum "project.clj" }}

      - run: sudo apt update && sudo apt install graphviz
      - run: lein kaocha --plugin cloverage --codecov

      - store_artifacts:
          path: target/coverage

      - run:
          name: Upload test coverage report to Codecov
          command: bash <(curl -s https://codecov.io/bash)

  publish_topologies:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - grapher-{{ checksum "project.clj" }}
      - run: lein run -m topology-grapher.topology

  checkout_tags:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - grapher-{{ checksum "project.clj" }}

      # Workaround required for https://discuss.circleci.com/t/22437
      #
      # This is required to prevent the warning that appears about connecting
      # to a host for the first time when we attempt to fetch the tags from
      # github.
      #
      # The `add-key` script checks the fingerprint of the ssh key returned
      # by github against the fingerprint published below on their website
      # to protect against MITM attacks
      #
      #  https://help.github.com/en/articles/githubs-ssh-key-fingerprints
      #
      - run: |
          .circleci/bin/add-key github.com $GITHUB_SSH_FINGERPRINT
          git fetch --force origin "refs/tags/${CIRCLE_TAG}:refs/tags/${CIRCLE_TAG}"

  deploy:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - grapher-{{ checksum "project.clj" }}

      - run:
          name: Prepare signing key
          command: |
            echo $GPG_PRIVATE_KEY |base64 --decode |gpg --yes --batch --import

      - run:
          name: Deploy to Clojars
          command: lein do jar, pom, deploy clojars
          environment:
            LEIN_GPG: /home/circleci/topology-grapher/.circleci/bin/gpg
            REAL_GPG: /usr/bin/gpg

  deploy_snapshot:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - grapher-{{ checksum "project.clj" }}

      - run:
          name: Deploy to Clojars
          command: |
            [ -z "$CLOJARS_USERNAME" ] || lein do jar, pom, deploy clojars

workflows:
  version: 2
  test-then-deploy:
    jobs:
      - test
      - coverage
      - checkout_tags
      - publish_topologies

      - deploy_snapshot:
          context: clojars-deploy
          requires:
            - test
          filters:
            tags:
              ignore: /.*/
            branches:
              ignore: /master/

      - deploy:
          context: clojars-deploy
          requires:
            - checkout_tags
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
